// <auto-generated />
using System;
using Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613203604_SeededCategoryData")]
    partial class SeededCategoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d6cfb81-7e4c-4b4f-9fe6-f31afb8f2e28"),
                            HexColor = "#34C759",
                            Icon = "cart.fill",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Jedzenie"
                        },
                        new
                        {
                            Id = new Guid("6a894c27-f13c-4fb0-8885-93c3890aec4a"),
                            HexColor = "#FF9500",
                            Icon = "fork.knife",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Restauracje"
                        },
                        new
                        {
                            Id = new Guid("d5d42cd6-e4a5-49ed-9ab9-fb8c54eb7c32"),
                            HexColor = "#007AFF",
                            Icon = "car.fill",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = new Guid("551a65d9-cfac-402b-a9f1-22d242f36f9a"),
                            HexColor = "#5856D6",
                            Icon = "house.fill",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Mieszkanie i rachunki"
                        },
                        new
                        {
                            Id = new Guid("d3530310-5b29-4557-90ac-65c382fbab3c"),
                            HexColor = "#FF2D55",
                            Icon = "cross.case.fill",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Zdrowie"
                        },
                        new
                        {
                            Id = new Guid("750a22e8-4105-403b-a895-a6f46efb767d"),
                            HexColor = "#AF52DE",
                            Icon = "gamecontroller.fill",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Rozrywka"
                        },
                        new
                        {
                            Id = new Guid("69d087e3-42ce-48e8-93d9-ba6f3af0ed4d"),
                            HexColor = "#FF3B30",
                            Icon = "bag.fill",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Zakupy"
                        },
                        new
                        {
                            Id = new Guid("e0f98104-b4a1-4ab3-af15-d9b802575f2d"),
                            HexColor = "#5AC8FA",
                            Icon = "repeat.circle.fill",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Subskrypcje"
                        },
                        new
                        {
                            Id = new Guid("19b3ccec-b173-4d75-b476-0808aa740a7f"),
                            HexColor = "#32ADE6",
                            Icon = "book.fill",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Edukacja"
                        },
                        new
                        {
                            Id = new Guid("f786c317-4bd0-452d-8839-117f4a2b0c16"),
                            HexColor = "#32ADE6",
                            Icon = "airplane",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Podróże"
                        },
                        new
                        {
                            Id = new Guid("44bfe6b9-6c7d-4b53-8aec-c66cf722a005"),
                            HexColor = "#8E8E93",
                            Icon = "tag.fill",
                            IsArchived = false,
                            IsDefault = true,
                            Name = "Inne"
                        });
                });

            modelBuilder.Entity("Api.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Api.Domain.Transaction", b =>
                {
                    b.HasOne("Api.Domain.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Api.Domain.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
